[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Gareth Adams <g@rethada.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
